BIN_HOME_RELEASE="/tmp/RayJoin/cmake-build-release-dl190"
BIN_HOME_DEBUG="/tmp/RayJoin/cmake-build-debug-dl190"
DATASET_ROOT="/local/storage/liang/rt_datasets/cdb"
MAPS=(Aquifers.cdb dtl_cnty.cdb Parks.cdb USACensusBlockGroupBoundaries.cdb USAZIPCodeArea.cdb USADetailedWaterBodies.cdb)
MAPS1=(Aquifers.cdb Parks.cdb USAZIPCodeArea.cdb)
MAPS2=(dtl_cnty.cdb USACensusBlockGroupBoundaries.cdb USADetailedWaterBodies.cdb)
DEFAULT_GRID_SIZE=2048
SERIALIZE_PREFIX="/dev/shm"
DEFAULT_XSECT_FACTOR="0.5"
DEFAULT_WIN_SIZE=32
DEFAULT_ENLARGE_LIM=2